### ISSUE TITLE
Filtered actions + redux-devtools-log-monitor displays states from incorrect actions

### ISSUE THREAD

**Issue by thomasboyt** [zalmoxisus/redux-devtools-filter-actions#4]
I'm working on a game using redux. The game has its own run loop that dispatches a `TICK` action inside a `requestAnimationFrame` loop, so I was planning to use this component to filter that action.

I was surprised to see that when I triggered a non-tick action, causing an entry to display in the devtools monitor, the state that was reported seemed to be stale, as if it was computed from one of the first tick actions. Investigating the source of `redux-devtools-log-monitor` and `redux-devtools-filter-actions`, I quickly saw the problem:
- In [FilterMonitor.js](https://github.com/zalmoxisus/redux-devtools-filter-actions/blob/master/src/FilterMonitor.js#L18), the `stagedActionIds` array is filtered to remove blacklisted/include whitelisted actions.
- In [LogMonitor.js](https://github.com/gaearon/redux-devtools-log-monitor/blob/master/src/LogMonitor.js#L176-L179), the `stagedActionIds` array is iterated over. The **index** of this iteration is used to look up the corresponding state from the `computedStates` passed from redux-devtools. However, `computedStates` contains _all of the computed states_, including blacklisted actions, meaning there's no way that this lookup will align with the filtered action IDs!

I'm not sure what the fix here is. I don't currently see any way to look up the correct `computedState` without having the index of the action. Maybe a map of action ID to state could be added to the props passed down from redux-devtools? A map of action ID to original index could also work.

**Comment by thomasboyt** [comment]
for now, I've solved this with a fork of redux-devtools-log-monitor: https://github.com/thomasboyt/redux-devtools-log-monitor/commit/35be43150bfca3369f33a049262ea219a1009fed

**Comment by zalmoxisus** [comment]
Hey @thomasboyt,

Your solution is the same as [it was here before extending it to a wrap monitor](https://github.com/zalmoxisus/redux-devtools-filter-actions/commit/1c48edf51cbba4025b59b22c253e5e5337ab6e6a). The reason we switched from that is to support different monitors and to have new versions of log monitor supported without maintaining a fork.

I figure filtering `computedStates` along with `stagedActionIds` will solve it.

**Comment by zalmoxisus** [comment]
Fixed in `v1.0.1`. Thanks for reporting this! Feel free to reopen the issue if something goes wrong.

**Comment by thomasboyt** [comment]
Awesome, thanks for such a fast response! Fix seems to work perfectly :)
